/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

type AccessTokenResponse struct {
	Expires string `json:".expires,omitempty"`
	AccessToken string `json:"access_token,omitempty"`
	Issued string `json:".issued,omitempty"`
	ClientRefreshTokenLifeTimeInMinutes string `json:"clientRefreshTokenLifeTimeInMinutes,omitempty"`
	ExpiresIn int64 `json:"expires_in,omitempty"`
	TokenType string `json:"token_type,omitempty"`
	ClientId string `json:"client_id,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
}
