/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud
// ColladaTransformStyle : The node's transform style of node.
type ColladaTransformStyle int32

// List of ColladaTransformStyle
const (
	ColladaTransformStyle_Components ColladaTransformStyle = 0
	ColladaTransformStyle_Matrix ColladaTransformStyle = 1
)
