/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

type Cylinder struct {
	// Gets or sets the name of the cylinder             
	Name string `json:"Name,omitempty"`
	// Gets or sets the radius of cylinder's top cap.
	RadiusTop float64 `json:"RadiusTop"`
	// Gets or sets the radius bottoof cylinder's bottom cap.             
	RadiusBottom float64 `json:"RadiusBottom"`
	// Gets or sets the height of the cylinder.
	Height float64 `json:"Height"`
	// Gets or sets the radial segments.
	RadialSegments int32 `json:"RadialSegments"`
	// Gets or sets the height segments.
	HeightSegments int32 `json:"HeightSegments"`
	// Gets or sets a value indicating whether this Aspose.ThreeD.Entities.Cylinder open ended. The default value is false.
	OpenEnded bool `json:"OpenEnded"`
	// Gets or sets the theta start. The default value is 0.             
	ThetaStart float64 `json:"ThetaStart"`
	// Gets or sets the length of the theta. The default value is 2p
	ThetaLength float64 `json:"ThetaLength"`
}
