/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud
// DracoCompressionLevel : Compression level for draco file
type DracoCompressionLevel int32

// List of DracoCompressionLevel
const (
	DracoCompressionLevel_NoCompression DracoCompressionLevel = 0
	DracoCompressionLevel_Fast DracoCompressionLevel = 1
	DracoCompressionLevel_Standard DracoCompressionLevel = 2
	DracoCompressionLevel_Optimal DracoCompressionLevel = 3
)
