/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud
// FileContentType : File content type
type FileContentType int32

// List of FileContentType
const (
	FileContentType_Binary FileContentType = 0
	FileContentType_ASCII FileContentType = 1
)
