/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

type GltfSaveOption struct {
	// Gets or sets  of the SaveFormat.
	SaveFormat SaveFormat `json:"SaveFormat,omitempty"`
	// Some files like OBJ depends on external file, the lookup paths will allows Aspose.3D to look for external file to load
	LookupPaths []string `json:"LookupPaths,omitempty"`
	// The file name of the exporting/importing scene. This is optional, but useful when serialize external assets like OBJ's material.
	FileName string `json:"FileName,omitempty"`
	// The file format like FBX,U3D,PDF ....
	FileFormat string `json:"FileFormat,omitempty"`
	// The JSON content of GLTF file is indented for human reading, default value is false.
	PrettyPrint bool `json:"PrettyPrint,omitempty"`
	// Embed all external assets as base64 into single file in ASCII mode, default value is false.
	EmbedAssets bool `json:"EmbedAssets,omitempty"`
	// Serialize materials using KHR common material extensions, default value is false. Set this to false will cause Aspose.3D export a set of vertex/fragment shader if Aspose.ThreeD.Formats.GLTFSaveOptions.ExportShaders
	UseCommonMaterials bool `json:"UseCommonMaterials,omitempty"`
	// Flip texture coordinate v(t) component, default value is true.
	FlipTexCoordV bool `json:"FlipTexCoordV,omitempty"`
	// The file name of the external buffer file used to store binary data. If this file is not specified, Aspose.3D will generate a name for you. This is ignored when export glTF in binary mode.
	BufferFile bool `json:"BufferFile,omitempty"`
	// Save scene object's dynamic properties into 'extra' fields in the generated glTF file. This is useful to provide application-specific data. Default value is false..
	SaveExtras bool `json:"SaveExtras,omitempty"`
	// Gets or sets whether to enable draco compression.
	DracoCompression bool `json:"DracoCompression,omitempty"`
	// Gets or sets  of the FileContent type.
	FileContentType *FileContentType `json:"FileContentType,omitempty"`
}
