/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

type HtmlSaveOption struct {
	// Gets or sets  of the SaveFormat.
	SaveFormat SaveFormat `json:"SaveFormat,omitempty"`
	// Some files like OBJ depends on external file, the lookup paths will allows Aspose.3D to look for external file to load
	LookupPaths []string `json:"LookupPaths,omitempty"`
	// The file name of the exporting/importing scene. This is optional, but useful when serialize external assets like OBJ's material.
	FileName string `json:"FileName,omitempty"`
	// The file format like FBX,U3D,PDF ....
	FileFormat string `json:"FileFormat,omitempty"`
	//  Display a grid in the scene. Default value is true.
	ShowGrid bool `json:"ShowGrid,omitempty"`
	//  Display rulers of x/y/z axises in the scene to measure the model. Default value is false
	ShowRulers bool `json:"ShowRulers,omitempty"`
	// Display a simple UI in the scene. Default value is true
	ShowUI bool `json:"ShowUI,omitempty"`
	// Display a orientation box. Default value is true.
	OrientationBox bool `json:"OrientationBox,omitempty"`
	// Gets or sets the up vector, value can be \"x\"/\"y\"/\"z\", default value is \"y\".
	UpVector string `json:"UpVector,omitempty"`
	// Gets or sets the far plane of the camera, default value is 1000
	FarPlane float64 `json:"FarPlane,omitempty"`
	// Gets or sets the near plane of the camera, default value is 1
	NearPlane float64 `json:"NearPlane,omitempty"`
	// Gets or sets the default look at position, default value is (0, 0, 0)
	LookAt *Vector3 `json:"LookAt,omitempty"`
	// Gets or sets the initial position of the camera, default value is (10, 10, 10)
	CameraPosition *Vector3 `json:"CameraPosition,omitempty"`
	//  Gets or sets the field of the view, default value is 45, measured in degree
	FieldOfView float64 `json:"FieldOfView,omitempty"`
}
