/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

// Parametric Modeling
type ModelData struct {
	// e.g Node
	Type_ string `json:"Type,omitempty"`
	Transform *Transform `json:"Transform,omitempty"`
	Entity *Entity `json:"Entity,omitempty"`
}
