/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud
// PdfRenderMode : Render mode specifies the style in which the 3D artwork is rendered.
type PdfRenderMode int32

// List of PdfRenderMode
const (
	PdfRenderMode_Solid PdfRenderMode = 0
	PdfRenderMode_SolidWireframe PdfRenderMode = 1
	PdfRenderMode_Transparent PdfRenderMode = 2
	PdfRenderMode_TransparentWireframe PdfRenderMode = 3
	PdfRenderMode_BoundingBox PdfRenderMode = 4
	PdfRenderMode_TransparentBoundingBox PdfRenderMode = 5
	PdfRenderMode_TransparentBoundingBoxOutline PdfRenderMode = 6
	PdfRenderMode_Wireframe PdfRenderMode = 7
	PdfRenderMode_ShadedWireframe PdfRenderMode = 8
	PdfRenderMode_HiddenWireframe PdfRenderMode = 9
	PdfRenderMode_Vertices PdfRenderMode = 10
	PdfRenderMode_ShadedVertices PdfRenderMode = 11
	PdfRenderMode_Illustration PdfRenderMode = 12
	PdfRenderMode_SolidOutline PdfRenderMode = 13
	PdfRenderMode_ShadedIllustration PdfRenderMode = 14
)
