/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud
// PdfLightingScheme : Render mode specifies the style in which the 3D artwork is rendered.
type PdfLightingScheme int32

// List of PdfLightingScheme
const (
	PdfLightingScheme_Artwork PdfLightingScheme = 0
	PdfLightingScheme_None PdfLightingScheme = 1
	PdfLightingScheme_White PdfLightingScheme = 2
	PdfLightingScheme_Day PdfLightingScheme = 3
	PdfLightingScheme_Night PdfLightingScheme = 4
	PdfLightingScheme_Hard PdfLightingScheme = 5
	PdfLightingScheme_Primary PdfLightingScheme = 6
	PdfLightingScheme_Blue PdfLightingScheme = 7
	PdfLightingScheme_Red PdfLightingScheme = 8
	PdfLightingScheme_Cube PdfLightingScheme = 8
	PdfLightingScheme_CAD PdfLightingScheme = 10
	PdfLightingScheme_Headlamp PdfLightingScheme = 11
)
