/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

// Plane Entity
type Plane struct {
	// The name of Plane
	Name string `json:"Name,omitempty"`
	// Gets or sets the length of the plane.             
	Length float64 `json:"Length"`
	// Gets or sets the width of the plane             
	Width float64 `json:"Width"`
	// Gets or sets the length segments.             
	LengthSegments int32 `json:"LengthSegments"`
	// Gets or sets the width segments.
	WidthSegments int32 `json:"WidthSegments"`
}
