/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

type PlySaveOption struct {
	// Gets or sets  of the SaveFormat.
	SaveFormat SaveFormat `json:"SaveFormat,omitempty"`
	// Some files like OBJ depends on external file, the lookup paths will allows Aspose.3D to look for external file to load
	LookupPaths []string `json:"LookupPaths,omitempty"`
	// The file name of the exporting/importing scene. This is optional, but useful when serialize external assets like OBJ's material.
	FileName string `json:"FileName,omitempty"`
	// The file format like FBX,U3D,PDF ....
	FileFormat string `json:"FileFormat,omitempty"`
	// Flip the coordinate while saving the scene, default value is true.
	FlipCoordinate bool `json:"FlipCoordinate,omitempty"`
	// The element name for the vertex data, default value is \"vertex\".
	VertexElement string `json:"VertexElement,omitempty"`
	// The component names for position data, default value is (\"x\", \"y\", \"z\")
	PositionComponents []string `json:"PositionComponents,omitempty"`
	// The element name for the face data, default value is face.
	FaceElement string `json:"FaceElement,omitempty"`
	// The property name for the face data, default value is vertex_index.
	FaceProperty string `json:"FaceProperty,omitempty"`
	// Gets or sets  of the FileContent Style.
	FileContentType *FileContentType `json:"FileContentType,omitempty"`
}
