/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud
// SaveFormat : SaveFormat type
type SaveFormat int32

// List of SaveFormat
const (
	SaveFormat_AMF SaveFormat = 0
	SaveFormat_ASE SaveFormat = 1
	SaveFormat_Aspose3DWeb SaveFormat = 2
	SaveFormat_Collada SaveFormat = 3
	SaveFormat_Discreet3DS SaveFormat = 4
	SaveFormat_Draco SaveFormat = 5
	SaveFormat_DXF SaveFormat = 6	
	SaveFormat_FBX SaveFormat = 7
	SaveFormat_GLTF SaveFormat = 8
	SaveFormat_HTML SaveFormat = 9
	SaveFormat_Microsoft3MF SaveFormat = 10		
	SaveFormat_JT SaveFormat = 11		
	SaveFormat_Obj SaveFormat = 12
	SaveFormat_PDF SaveFormat = 13
	SaveFormat_PLY SaveFormat = 14
	SaveFormat_Rvm SaveFormat = 15
	SaveFormat_STL SaveFormat = 16
	SaveFormat_U3D SaveFormat = 17
	SaveFormat_VRML SaveFormat = 18
	SaveFormat_X SaveFormat = 19
)
