/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

// The Torus Entity class
type Torus struct {
	// Gets or sets the Name of the torus.
	Name string `json:"Name,omitempty"`
	// Gets or sets the radius of the torus.             
	Radius float64 `json:"Radius"`
	// Gets or sets the radius of the tube.
	Tube float64 `json:"Tube"`
	// Gets or sets the radial segments.
	RadialSegments int32 `json:"RadialSegments"`
	// Gets or sets the tubular segments.
	TubularSegments int32 `json:"TubularSegments"`
	// Gets or sets the arc.
	Arc float64 `json:"Arc"`
}
