/*
 * Aspose.3D Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package aspose3dcloud

// A vector with three components.             
type Vector3 struct {
	// The x component.
	X float64 `json:"x"`
	// The y component.
	Y float64 `json:"y"`
	// The z component.
	Z float64 `json:"z"`
	// Gets the square of the length.             
	Length2 float64 `json:"Length2"`
	// Gets the length of this vector.
	Length float64 `json:"Length"`
}
